project:
  type: website

website:
  title: pysps
  site-url: https://marberts.github.io/pysps
  description: Sequential Poisson sampling in Python
  navbar:
    logo: logo.png
    left:
      - file: get-started.qmd
        text: Getting started
      - href: reference/index.qmd
        text: References

    right:
      - icon: github
        href: https://github.com/marberts/pysps

format:
  html:
    toc: true
    theme: cosmo
    css:
      - reference/_styles-quartodoc.css

quartodoc:
  package: pysps
  dir: reference
  style: pkgdown
  css: reference/_styles-quartodoc.css
  renderer:
    style: markdown
    table_style: description-list

  sections:
    - title: Inclusion probabilities
      desc: Functions and classes to calculate first-order inclusion probabilities.
      contents:
        - InclusionProb
        - becomes_ta
    - title: Draw a sample
      desc: Classes to draw sequential and ordinary Poisson samples.
      contents:
        - OrderSample
        - PoissonSample
    - title: Stratification
      desc: Make an allocation for stratified sampling.
      contents:
        - prop_allocation
        - divisor_method